name: CI - Build, Test, and Push Docker Image

on:
  push:
    branches: master
    tags: 'v*'
  pull_request:
    branches: master

env:
  IMAGE_NAME: hazelcast/simulator
  PYTHON_VERSION: "3.11"
  TEST_IMAGE_TAG: test-image:latest
  DOCKER_PLATFORMS: linux/amd64,linux/arm64
  TEST_PLATFORM: linux/amd64

jobs:
  docker-ci:
    name: Docker Build, Test, and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1
        with:
          platforms: ${{ env.DOCKER_PLATFORMS }}

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5.8.0
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Setup Java
        uses: actions/setup-java@v4.7.1
        env:
          HZ_SNAPSHOT_INTERNAL_USERNAME: ${{ secrets.HZ_SNAPSHOT_INTERNAL_USERNAME }}
          HZ_SNAPSHOT_INTERNAL_PASSWORD: ${{ secrets.HZ_SNAPSHOT_INTERNAL_PASSWORD }}

        with:
          java-version: '17'
          distribution: 'termurin'
          cache: 'maven'
          server-id: snapshot-internal
          server-username: HZ_SNAPSHOT_INTERNAL_USERNAME
          server-password: HZ_SNAPSHOT_INTERNAL_PASSWORD
          
      - name: Setup Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Build Java artifacts (required for Docker build)
        run: |
          echo "Building Java components..."
          ./build
        timeout-minutes: 15  # Prevents infinite hangs on Maven dependency resolution failures

      - name: Build Docker image for testing
        uses: docker/build-push-action@v5.4.0
        with:
          context: .
          platforms: ${{ env.TEST_PLATFORM }}
          load: true
          tags: ${{ env.TEST_IMAGE_TAG }}
          build-args: |
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
          # Only cache for main branch builds to avoid PR cache overhead and branch isolation issues
          cache-from: ${{ github.ref == 'refs/heads/master' && 'type=gha' || '' }}
          cache-to: ${{ github.ref == 'refs/heads/master' && 'type=gha,mode=max' || '' }}

      - name: Run container smoke tests
        run: |
          echo "Running container smoke tests..."
          
          # Test container startup and basic functionality
          echo "Testing container startup..."
          CONTAINER_ID=$(docker run --rm -d ${{ env.TEST_IMAGE_TAG }} sleep 30)
          
          # Wait for container to be healthy using HEALTHCHECK
          echo "Waiting for container to be healthy..."
          timeout 60 bash -c 'until [ "$(docker inspect "${CONTAINER_ID}" --format="{{.State.Health.Status}}")" = "healthy" ]; do sleep 2; done'
          
          # Test basic commands are available
          echo "Testing Java installation..."
          docker exec "${CONTAINER_ID}" java -version
          
          echo "Testing Maven installation..."
          docker exec "${CONTAINER_ID}" mvn --version
          
          echo "Testing Python installation..."
          docker exec "${CONTAINER_ID}" python${{ env.PYTHON_VERSION }} --version
          
          echo "Testing Terraform installation..."
          docker exec "${CONTAINER_ID}" terraform version
          
          echo "Testing AWS CLI installation..."
          docker exec "${CONTAINER_ID}" aws --version
          
          echo "Testing simulator commands availability..."
          docker exec "${CONTAINER_ID}" which perftest
          docker exec "${CONTAINER_ID}" which inventory
          
          echo "Testing simulator welcome message..."
          docker exec "${CONTAINER_ID}" /opt/simulator/bin/simulator-welcome
          
          echo "Testing perftest help command..."
          docker exec "${CONTAINER_ID}" perftest --help || true
          
          echo "Testing inventory help command..."
          docker exec "${CONTAINER_ID}" inventory --help || true
          
          # Stop container 
          docker stop "${CONTAINER_ID}"
          
          echo "Smoke tests completed successfully!"

      - name: Build and push multi-platform Docker image
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v5.4.0
        with:
          context: .
          platforms: ${{ env.DOCKER_PLATFORMS }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
          # Only cache for main branch builds to avoid PR cache overhead and branch isolation issues
          cache-from: ${{ github.ref == 'refs/heads/master' && 'type=gha' || '' }}
          cache-to: ${{ github.ref == 'refs/heads/master' && 'type=gha,mode=max' || '' }}

      - name: Generate build summary
        if: always()
        run: |
          echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Image Details" >> $GITHUB_STEP_SUMMARY
          echo "- **Repository**: ${{ env.IMAGE_NAME }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Tags**: ${{ steps.meta.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Platforms**: ${{ env.DOCKER_PLATFORMS }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Test Results" >> $GITHUB_STEP_SUMMARY
          echo "- **Java Build**: Completed" >> $GITHUB_STEP_SUMMARY
          echo "- **Container Smoke Tests**: Passed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ "${{ github.event_name }}" != "pull_request" ]; then
            echo "### Published Images" >> $GITHUB_STEP_SUMMARY
            echo "The following images have been published:" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            echo "${{ steps.meta.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### Usage" >> $GITHUB_STEP_SUMMARY
            echo '```bash' >> $GITHUB_STEP_SUMMARY
            echo "# Pull and run the latest image" >> $GITHUB_STEP_SUMMARY
            echo "docker run -it --rm ${{ env.IMAGE_NAME }}:latest" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          fi
